version: "3.8"

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    networks:
      - webnet
      - nginx_network
    expose:
      - 3000
    volumes:
      - /app/node_modules/
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:3000/"]
      interval: 1m
      timeout: 5s
      retries: 2

  web: &web
    container_name: web
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    networks:
      - webnet
      - nginx_network
    expose:
      - 8000
    environment:
      DATABASE_PORT: '5432'
    env_file:
      - ./config/.env
    restart: on-failure
    command: sh /gunicorn.sh
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:8000/admin/login/"]
      interval: 1m
      timeout: 5s
      retries: 2


  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: on-failure
    networks:
      - nginx_network
    ports:
      - 80:80
    depends_on:
      - web
      - frontend
    healthcheck:
      test: ["CMD-SHELL", "ps ax", "|" ,"grep -v grep", "|" ,"grep nginx",  "||", "exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  webnet:
  nginx_network:
